Repository UMC-7th-A1Grade/FrontEnd, pull requests merged in 2025-02, with the labels that each got.

#51 ✨ Feat : 공학용 계산기 UI 제작 및 카메라 페이지 api 연동
  public/upload.png
  src/components/global/Calculator.jsx
  src/components/global/Calculator.module.css
  src/pages/CameraPage.jsx
  src/styles/cameraPage/CameraPage.module.css
Labels: enhancement

#50 [Feat/#37] 최근 5문제 팝업 제작 / 이미지 갯수별 화면 제작
  package-lock.json
  package.json
  src/apis/axios.js
  src/assets/images/home/X_button.svg
  src/components/Auth/AuthCallback.jsx
  src/components/CharacterSelectPage/CharacterBox/CharacterBox.jsx
  src/components/CharacterSelectPage/CharacterBox/CharacterBox.module.css
  src/components/HomePage/FullPopup/FullPopup.jsx
  src/components/HomePage/FullPopup/FullPopup.module.css
  src/components/HomePage/ImageSlider/ImageSlider.jsx
  src/components/HomePage/ImageSlider/ImageSlider.module.css
  src/components/HomePage/SlideCircle/SlideCircle.jsx
  src/components/HomePage/SlideCircle/SlideCircle.module.css
  src/components/HomePage/SmallPopup/SmallPopup.jsx
  src/components/HomePage/SmallPopup/SmallPopup.module.css
  src/components/LoginPage/LoginButton.jsx
  src/components/NickNamePage/NextButton/NextButton.jsx
  src/components/NickNamePage/NicknameInput/NicknameInput.jsx
  src/components/NickNamePage/NicknameInput/NicknameInput.module.css
  src/pages/GoogleCallbackPage.jsx
  src/pages/HomePage.jsx
  src/pages/NickNamePage.jsx
  src/routes/Routes.jsx
  src/styles/CharacterSelectPage/CharacterSelectPage.module.css
  src/styles/LoginStyles/GoogleLoginButton.module.css
  src/styles/LoginStyles/Login.module.css
  src/styles/LoginStyles/LogoAni.module.css
  src/styles/NicknameStyles/NickName.module.css
  src/utils/api.jsx
  vite.config.js
Labels: enhancement

#91 [Feat] 최근 5문제 api 연결 진행 중
  src/apis/questionApi.js
  src/components/HomePage/ImageSlider/ImageSlider.jsx
  src/pages/HomePage.jsx
Labels: enhancement, backend

#97 ✨ Feat: 재로그인 시 메인으로 연결
  src/pages/GoogleCallbackPage.jsx
Labels: api

#98 🐛 Bug: 토큰-메인연결 오류
  src/pages/GoogleCallbackPage.jsx
Labels: api

#100 🐛 Bug: 메인 화면 500에러 해결을 위한 디버깅 코드 추가
  src/apis/questionApi.js
  src/components/HomePage/ImageSlider/ImageSlider.jsx
Labels: api

#104 ✨ Feat : 마이페이지 api 연동
  src/apis/myPage/index.js
  src/components/common/Loading.jsx
  src/pages/MyPage.jsx
Labels: api

#123 🐛 Fix : 크레딧 오류 해결
  public/images/home/chatbot.png
  public/images/home/credit.png
  public/images/login/google_logo.png
  public/images/nickname/Logo_Nickname.png
  src/apis/userApi.js
  src/components/HomePage/CreditButton/CreditButton.jsx
  src/components/HomePage/FullPopup/FullPopup.jsx
  src/components/HomePage/SmallPopup/SmallPopup.jsx
Labels: api
